/**
 * Pool curato di film "candidati" per il Film del Giorno.
 *
 * Vengono usati ID TMDb reali delle opere più celebri/popolari.
 * La selezione giornaliera è deterministica: index = seededInt(date, pool.length).
 *
 * Se desideri estendere la lista, aggiungi coppie { id, title } e controlla
 * che l'ID esista davvero su TMDb, ad esempio con `npm run verify:pool`.
 */

export interface PoolMovie {
  id: number;
  title: string;
}

export const MOVIE_POOL: PoolMovie[] = [
  // ---- Classici immortali ----
  { id: 278, title: 'Le ali della libertà (The Shawshank Redemption)' },
  { id: 238, title: 'Il padrino' },
  { id: 240, title: 'Il padrino - Parte II' },
  { id: 242, title: 'Il padrino - Parte III' },
  { id: 155, title: 'Il cavaliere oscuro' },
  { id: 680, title: 'Pulp Fiction' },
  { id: 13, title: 'Forrest Gump' },
  { id: 424, title: "Schindler's List - La lista di Schindler" },
  { id: 597, title: 'Titanic' },
  { id: 274, title: 'Il silenzio degli innocenti' },
  { id: 550, title: 'Fight Club' },
  { id: 428, title: 'Arancia meccanica' },
  { id: 62, title: '2001: Odissea nello spazio' },
  { id: 694, title: 'Shining' },
  { id: 539, title: 'Psycho' },
  { id: 400, title: 'La donna che visse due volte (Vertigo)' },
  { id: 289, title: 'Casablanca' },
  { id: 15, title: 'Quarto potere (Citizen Kane)' },
  { id: 72, title: 'Taxi Driver' },
  { id: 14, title: 'American Beauty' },
  { id: 630, title: 'Il mago di Oz' },
  { id: 834, title: 'Il laureato' },
  { id: 769, title: 'Goodfellas - Quei bravi ragazzi' },
  { id: 524, title: 'Casinò' },
  { id: 807, title: 'Seven' },
  { id: 629, title: 'I soliti sospetti' },
  { id: 949, title: 'Heat - La sfida' },
  { id: 111, title: 'Scarface' },
  { id: 500, title: 'Le iene (Reservoir Dogs)' },
  { id: 770, title: 'Via col vento' },
  { id: 774, title: 'Cantando sotto la pioggia' },
  { id: 745, title: 'Il sesto senso' },
  { id: 619, title: 'Rocky' },
  { id: 1366, title: 'Rocky II' },
  { id: 1367, title: 'Rocky III' },
  { id: 1368, title: 'Rocky IV' },
  { id: 581, title: 'Balla coi lupi' },
  { id: 948, title: "L'ultimo dei Mohicani" },
  { id: 1359, title: 'Il mistero del falco' },
  { id: 976, title: 'Viale del tramonto (Sunset Blvd)' },
  { id: 578, title: 'Lo squalo' },
  { id: 601, title: "E.T. l'extra-terrestre" },
  { id: 840, title: 'Incontri ravvicinati del terzo tipo' },
  { id: 114, title: 'Pretty Woman' },

  // ---- Fantascienza & Avventura ----
  { id: 603, title: 'Matrix' },
  { id: 604, title: 'Matrix Reloaded' },
  { id: 605, title: 'Matrix Revolutions' },
  { id: 78, title: 'Blade Runner' },
  { id: 335984, title: 'Blade Runner 2049' },
  { id: 348, title: 'Alien' },
  { id: 679, title: 'Aliens - Scontro finale' },
  { id: 218, title: 'Terminator' },
  { id: 280, title: 'Terminator 2 - Il giorno del giudizio' },
  { id: 27205, title: 'Inception' },
  { id: 157336, title: 'Interstellar' },
  { id: 19995, title: 'Avatar' },
  { id: 76600, title: "Avatar - La via dell'acqua" },
  { id: 11, title: 'Guerre stellari' },
  { id: 1891, title: "L'impero colpisce ancora" },
  { id: 1892, title: 'Il ritorno dello Jedi' },
  { id: 1893, title: 'La minaccia fantasma' },
  { id: 1894, title: "L'attacco dei cloni" },
  { id: 1895, title: 'La vendetta dei Sith' },
  { id: 140607, title: 'Star Wars - Il risveglio della Forza' },
  { id: 181808, title: 'Star Wars - Gli ultimi Jedi' },
  { id: 181812, title: "Star Wars - L'ascesa di Skywalker" },
  { id: 330459, title: 'Rogue One: A Star Wars Story' },
  { id: 76341, title: 'Mad Max: Fury Road' },
  { id: 329, title: 'Jurassic Park' },
  { id: 135397, title: 'Jurassic World' },
  { id: 286217, title: 'The Martian - Sopravvissuto' },
  { id: 49047, title: 'Gravity' },
  { id: 329865, title: 'Arrival' },
  { id: 264660, title: 'Ex Machina' },
  { id: 18, title: 'Il quinto elemento' },
  { id: 861, title: 'Total Recall - Atto di forza' },

  // ---- Indy, Spie & Azione ----
  { id: 85, title: "I predatori dell'arca perduta" },
  { id: 87, title: 'Indiana Jones e il tempio maledetto' },
  { id: 89, title: "Indiana Jones e l'ultima crociata" },
  { id: 2176, title: 'Indiana Jones e il regno del teschio di cristallo' },
  { id: 954, title: 'Mission: Impossible' },
  { id: 177677, title: 'Mission: Impossible - Rogue Nation' },
  { id: 353081, title: 'Mission: Impossible - Fallout' },
  { id: 37724, title: 'Skyfall' },
  { id: 206647, title: 'Spectre' },
  { id: 98, title: 'Il gladiatore' },
  { id: 163, title: "Ocean's Eleven - Fate il vostro gioco" },
  { id: 1913, title: "Ocean's Twelve - Edizione speciale" },
  { id: 2757, title: "Ocean's Thirteen - Tutto o niente" },
  { id: 77, title: 'Memento' },
  { id: 1858, title: 'Transformers' },
  { id: 9799, title: 'The Fast and the Furious' },
  { id: 168259, title: 'Fast & Furious 7' },
  { id: 744, title: 'Top Gun' },
  { id: 361743, title: 'Top Gun: Maverick' },
  { id: 106, title: 'Predator' },
  { id: 754, title: 'Blade' },
  { id: 561, title: 'Constantine' },
  { id: 268, title: 'Batman' },
  { id: 1452, title: 'V per Vendetta' },
  { id: 13183, title: 'Watchmen' },
  { id: 107, title: 'Snatch - Lo strappo' },
  { id: 16858, title: 'RocknRolla' },
  { id: 64690, title: 'Drive' },
  { id: 857, title: 'Salvate il soldato Ryan' },
  { id: 497, title: 'Il miglio verde' },
  { id: 423, title: 'Il pianista' },
  { id: 1422, title: 'The Departed - Il bene e il male' },

  // ---- Trilogie fantasy / saga ----
  { id: 122, title: "Il Signore degli Anelli - La Compagnia dell'Anello" },
  { id: 120, title: 'Il Signore degli Anelli - Le due torri' },
  { id: 121, title: 'Il Signore degli Anelli - Il ritorno del re' },
  { id: 24, title: 'Kill Bill - Volume 1' },
  { id: 507, title: 'Kill Bill - Volume 2' },
  { id: 767, title: 'Harry Potter e la pietra filosofale' },
  { id: 672, title: 'Harry Potter e la camera dei segreti' },
  { id: 675, title: 'Harry Potter e il prigioniero di Azkaban' },
  { id: 674, title: 'Harry Potter e il calice di fuoco' },
  { id: 671, title: "Harry Potter e l'ordine della fenice" },
  { id: 12444, title: 'Harry Potter e il principe mezzosangue' },
  { id: 12445, title: 'Harry Potter e i doni della morte - Parte 1' },
  { id: 12446, title: 'Harry Potter e i doni della morte - Parte 2' },
  { id: 105, title: 'Ritorno al futuro' },
  { id: 16558, title: 'Ritorno al futuro - Parte II' },
  { id: 196, title: 'Ritorno al futuro - Parte III' },
  { id: 129, title: 'La città incantata (Spirited Away)' },
  { id: 128, title: 'La principessa Mononoke' },
  { id: 4935, title: 'Il castello errante di Howl' },
  { id: 12477, title: 'Il castello nel cielo' },
  { id: 8392, title: 'Il mio vicino Totoro' },
  { id: 149, title: 'Akira' },
  { id: 9325, title: 'Ghost in the Shell' },
  { id: 372058, title: 'Your Name' },
  { id: 843, title: 'Il labirinto del fauno' },
  { id: 83542, title: 'Cloud Atlas' },
  { id: 68726, title: 'Pacific Rim' },

  // ---- Supereroi ----
  { id: 24428, title: 'The Avengers' },
  { id: 299534, title: 'Avengers: Endgame' },
  { id: 299536, title: 'Avengers: Infinity War' },
  { id: 1726, title: 'Iron Man' },
  { id: 10138, title: 'Iron Man 2' },
  { id: 68721, title: 'Iron Man 3' },
  { id: 118340, title: 'Guardiani della Galassia' },
  { id: 283995, title: 'Guardiani della Galassia Vol. 2' },
  { id: 447365, title: 'Guardiani della Galassia Vol. 3' },
  { id: 284054, title: 'Black Panther' },
  { id: 505642, title: 'Black Panther: Wakanda Forever' },
  { id: 10195, title: 'Thor' },
  { id: 284053, title: 'Thor: Ragnarok' },
  { id: 616037, title: 'Thor: Love and Thunder' },
  { id: 284052, title: 'Doctor Strange' },
  { id: 453395, title: 'Doctor Strange nel Multiverso della Follia' },
  { id: 102899, title: 'Ant-Man' },
  { id: 363088, title: 'Ant-Man and the Wasp' },
  { id: 1771, title: 'Captain America - Il primo vendicatore' },
  { id: 271110, title: 'Captain America: Civil War' },
  { id: 299537, title: 'Captain Marvel' },
  { id: 497698, title: 'Black Widow' },
  { id: 524434, title: 'Eternals' },
  { id: 557, title: 'Spider-Man' },
  { id: 558, title: 'Spider-Man 2' },
  { id: 559, title: 'Spider-Man 3' },
  { id: 1930, title: 'The Amazing Spider-Man' },
  { id: 102382, title: 'The Amazing Spider-Man 2 - Il potere di Electro' },
  { id: 315635, title: 'Spider-Man: Homecoming' },
  { id: 429617, title: 'Spider-Man: Far from Home' },
  { id: 634649, title: 'Spider-Man: No Way Home' },
  { id: 324857, title: 'Spider-Man: Un nuovo universo' },
  { id: 569094, title: 'Spider-Man: Across the Spider-Verse' },
  { id: 293660, title: 'Deadpool' },
  { id: 383498, title: 'Deadpool 2' },
  { id: 533535, title: 'Deadpool & Wolverine' },
  { id: 475557, title: 'Joker' },
  { id: 414906, title: 'The Batman' },
  { id: 272, title: 'Batman Begins' },
  { id: 49026, title: 'Il cavaliere oscuro - Il ritorno' },
  { id: 335983, title: 'Venom' },
  { id: 297762, title: 'Aquaman' },
  { id: 36657, title: 'X-Men' },
  { id: 263115, title: 'Logan - The Wolverine' },
  { id: 246655, title: 'X-Men - Giorni di un futuro passato' },

  // ---- Animazione (Pixar / Disney / Illumination) ----
  { id: 862, title: 'Toy Story' },
  { id: 863, title: 'Toy Story 2' },
  { id: 10193, title: 'Toy Story 3' },
  { id: 301528, title: 'Toy Story 4' },
  { id: 12, title: 'Alla ricerca di Nemo' },
  { id: 10681, title: 'WALL-E' },
  { id: 14160, title: 'Up' },
  { id: 2062, title: 'Ratatouille' },
  { id: 9806, title: 'Gli Incredibili' },
  { id: 585, title: 'Monsters & Co.' },
  { id: 920, title: 'Cars - Motori ruggenti' },
  { id: 150689, title: 'Inside Out' },
  { id: 1022789, title: 'Inside Out 2' },
  { id: 354912, title: 'Coco' },
  { id: 508442, title: 'Soul' },
  { id: 976573, title: 'Elemental' },
  { id: 508943, title: 'Luca' },
  { id: 508947, title: 'Red (Turning Red)' },
  { id: 8587, title: 'Il re leone' },
  { id: 812, title: 'Aladdin' },
  { id: 10020, title: 'La bella e la bestia' },
  { id: 10144, title: 'La sirenetta' },
  { id: 10674, title: 'Mulan' },
  { id: 109445, title: 'Frozen - Il regno di ghiaccio' },
  { id: 301053, title: 'Frozen 2 - Il segreto di Arendelle' },
  { id: 277834, title: 'Oceania' },
  { id: 38757, title: "Rapunzel - L'intreccio della torre" },
  { id: 568124, title: 'Encanto' },
  { id: 527774, title: "Raya e l'ultimo drago" },
  { id: 82690, title: 'Ralph Spaccatutto' },
  { id: 404368, title: 'Ralph Spaccatutto 2' },
  { id: 177572, title: 'Big Hero 6' },
  { id: 269149, title: 'Zootropolis' },
  { id: 211672, title: 'Minions' },
  { id: 20352, title: 'Cattivissimo me' },
  { id: 335866, title: 'Sing' },
  { id: 76492, title: 'Hotel Transylvania' },

  // ---- Commedie ----
  { id: 8363, title: 'Superbad' },
  { id: 18785, title: 'Una notte da leoni' },
  { id: 12133, title: 'Fratellastri a 40 anni' },
  { id: 10625, title: 'Mean Girls' },
  { id: 1542, title: 'Office Space' },
  { id: 544, title: 'Tutto può succedere' },
  { id: 8699, title: 'Anchorman - La leggenda di Ron Burgundy' },
  { id: 4966, title: 'Napoleon Dynamite' },
  { id: 8467, title: 'Scemo & più scemo' },
  { id: 115, title: 'Il grande Lebowski' },
  { id: 620, title: 'Ghostbusters' },
  { id: 4011, title: 'Beetlejuice - Spiritello porcello' },
  { id: 771, title: "Mamma, ho perso l'aereo" },
  { id: 772, title: "Mamma, ho riperso l'aereo" },
  { id: 787, title: 'Mr. & Mrs. Smith' },
  { id: 2493, title: 'Pretty Princess' },
  { id: 848, title: 'Sister Act - Una svitata in abito da suora' },
  { id: 16, title: 'Balle spaziali' },
  { id: 9738, title: 'Fantozzi' },

  // ---- Horror ----
  { id: 419430, title: 'Scappa - Get Out' },
  { id: 458156, title: 'Noi (Us)' },
  { id: 493922, title: 'Hereditary - Le radici del male' },
  { id: 447332, title: 'A Quiet Place - Un posto tranquillo' },
  { id: 138843, title: "The Conjuring - L'evocazione" },
  { id: 91586, title: 'Insidious' },
  { id: 565, title: 'The Ring' },
  { id: 8006, title: 'Gremlins' },

  // ---- Contemporanei / Blockbuster recenti ----
  { id: 496243, title: 'Parasite' },
  { id: 438631, title: 'Dune' },
  { id: 693134, title: 'Dune - Parte due' },
  { id: 872585, title: 'Oppenheimer' },
  { id: 346698, title: 'Barbie' },
  { id: 545611, title: 'Everything Everywhere All at Once' },
  { id: 546554, title: 'Cena con delitto - Knives Out' },
  { id: 676547, title: 'Glass Onion' },
  { id: 530915, title: '1917' },
  { id: 245891, title: 'John Wick' },
  { id: 603692, title: 'John Wick 4' },
  { id: 522627, title: 'The Gentlemen' },
  { id: 19404, title: 'Django Unchained' },
  { id: 16869, title: 'Bastardi senza gloria' },
  { id: 244786, title: 'Whiplash' },
  { id: 313369, title: 'La La Land' },
  { id: 406997, title: 'Moonlight' },
  { id: 76203, title: '12 anni schiavo' },
  { id: 355216, title: 'Il caso Spotlight' },
  { id: 266856, title: 'La grande scommessa' },
  { id: 281957, title: 'The Revenant' },
  { id: 120467, title: 'The Grand Budapest Hotel' },
  { id: 194662, title: 'Birdman' },
  { id: 152601, title: 'Lei (Her)' },
  { id: 807, title: 'Seven - The Sette' }
];

/** Pool de-duplicato (protegge da id duplicati). */
export const MOVIE_POOL_UNIQUE: PoolMovie[] = (() => {
  const seen = new Set<number>();
  return MOVIE_POOL.filter((m) => {
    if (seen.has(m.id)) return false;
    seen.add(m.id);
    return true;
  });
})();

export const MOVIE_POOL_IDS: number[] = MOVIE_POOL_UNIQUE.map((m) => m.id);